### ISSUE TITLE
can't edit settings

### ISSUE THREAD

**Issue by wo** [peerdavid/remapy#45]
When I launch remapy (on Linux Mint), all the fields under 'Settings' are disabled, so I can't enter the one-time code. In the terminal, I see:

```
(Warning) Failed to publish subscriber.
'NoneType' object is not iterable
```

When I click in the 'Filter' field, I get:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/wo/install/remapy-master/gui/file_explorer.py", line 216, in filter_changed_event_handler
    root = self.item_manager.get_root()
  File "/home/wo/install/remapy-master/model/item_manager.py", line 41, in get_root
    self._clean_local_items(metadata_list)
  File "/home/wo/install/remapy-master/model/item_manager.py", line 147, in _clean_local_items
    online_ids = [metadata["ID"] for metadata in metadata_list]
TypeError: 'NoneType' object is not iterable
```

**Comment by peerdavid** [comment]
Can you check if you really execute the latest version of the source code? There was a problem with downloading data as the URL changed which produced exactly this problem but I fixed this a few weeks ago...

**Comment by wo** [comment]
Yes. I just tried again with the cloned current version. Same problem.

**Comment by peerdavid** [comment]
Can you also try to rename or delete the .emapy folder in your home dir? Then all settings and local files are deleted...

Thanks, David

**Comment by wo** [comment]
That worked! Thanks! 

Looks like the user_token field in config got somehow corrupted. In the old version it says

```
 user_token: <!doctype html><html><head><meta charset="utf-8"><meta name="viewport"
    content="width=device-width,initial-scale=1,user-scalable=no,minimum-scale=1,maximum-scale=1"><title>reMarkable
    &bull; Device Activation</title><link rel="shortcut icon" href="/assets/favicon.ico"><link
    rel="icon" type="image/png" sizes="16x16" href="/assets/favicon-16x16.png"><link
    rel="icon" type="image/png" sizes="32x32" href="/assets/favicon-32x32.png"><link
    rel="icon" type="image/png" sizes="48x48" href="/assets/favicon-48x48.png"><link
    rel="manifest" href="/assets/manifest.json"><meta name="mobile-web-app-capable"
    content="yes"><meta name="theme-color" content="#fff"><meta name="application-name"
    content="cloud-webapp-frontend"><link rel="apple-touch-icon" sizes="57x57" href="/assets/apple-touch-icon-57x57.png"><link
    rel="apple-touch-icon" sizes="60x60" href="/assets/apple-touch-icon-60x60.png"><link
    rel="apple-touch-icon" sizes="72x72" href="/assets/apple-touch-icon-72x72.png"><link
    rel="apple-touch-icon" sizes="76x76" href="/assets/apple-touch-icon-76x76.png"><link
    rel="apple-touch-icon" sizes="114x114" href="/assets/apple-touch-icon-114x114.png"><link
    rel="apple-touch-icon" sizes="120x120" href="/assets/apple-touch-icon-120x120.png"><link
    rel="apple-touch-icon" sizes="144x144" href="/assets/apple-touch-icon-144x144.png"><link
    rel="apple-touch-icon" sizes="152x152" href="/assets/apple-touch-icon-152x152.png"><link
    rel="apple-touch-icon" sizes="167x167" href="/assets/apple-touch-icon-167x167.png"><link
    rel="apple-touch-icon" sizes="180x180" href="/assets/apple-touch-icon-180x180.png"><link
    rel="apple-touch-icon" sizes="1024x1024" href="/assets/apple-touch-icon-1024x1024.png"><meta
    name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style"
    content="black-translucent"><meta name="apple-mobile-web-app-title" content="cloud-webapp-frontend"><meta
    name="msapplication-TileColor" content="#fff"><meta name="msapplication-TileImage"
    content="/assets/mstile-144x144.png"><meta name="msapplication-config" content="/assets/browserconfig.xml"><script
    defer="defer" src="/app-f9289d0e9f65654b3972.js"></script><link href="/app-71f2c21dbcf2b14a6828.css"
    rel="stylesheet"></head><body><div id="header"></div><div id="root"></div></body></html>
```

**Comment by peerdavid** [comment]
Ah great thank you also for the detailed traces. Yea this is exactly due to the url change - so a renew of the token points to the wrong url and returns this html which is then stored... therefore a "reset" is necessary :/

I will close this issue. Feel free to re-open it :)
