### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ZacharieALES** [peerdavid/remapy#5]
Hello,

When running "pip3 install -r requirements.txt" I get the following error:
```
...
Collecting cairocffi>=0.9.0

  Using cached cairocffi-1.1.0.tar.gz (68 kB)

  WARNING: Generating metadata for package cairocffi produced metadata for project name unknown. Fix your #egg=cairocffi fragments.

ERROR: Exception:

Traceback (most recent call last):

  File "/home/zach/10_Soft/remapy/env/lib/python3.5/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)

  File "/home/zach/10_Soft/remapy/env/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)

  File "/home/zach/10_Soft/remapy/env/lib/python3.5/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))

  File "/home/zach/10_Soft/remapy/env/lib/python3.5/site-packages/pip/_internal/legacy_resolve.py", line 370, in _resolve_one
    assert req_to_install.is_direct

AssertionError
```

Do you know what I did wrong? (or should do?)

**Comment by peerdavid** [comment]
You solved the problem (issue is closed)?

**Comment by ZacharieALES** [comment]
I thought I solved it, but no I still have this problem...

I tried to do installation steps 1 to 4. I also tried just step 4 and still have the same error.

**Comment by peerdavid** [comment]
I pushed a workaround as it seems that this problem is caused by the weasyprint package. Can you please try to pull the changes, delete the env folder and install it again? 

Note: With this workaround weasyprint is not installed only imported if needed i.e. currently you can not copy a url and paste it directly into RemaPy...

**Comment by ZacharieALES** [comment]
Thank you for your help.

I was now able to install all the requirements (by deleting the env folder and using steps 1 to 4). However, when I execute rema.py I get:
```
(env) zach@zach-dell-ensta ~/10_Soft/remapy/remapy $ ./rema.py 
Traceback (most recent call last):
  File "./rema.py", line 10, in <module>
    from gui.remarkable import Remarkable
  File "/home/zach/10_Soft/remapy/remapy/gui/remarkable.py", line 15, in <module>
    import api.remarkable_client
  File "/home/zach/10_Soft/remapy/remapy/api/remarkable_client.py", line 210
    "Authorization": f"Bearer {device_token}"
                                            ^
SyntaxError: invalid syntax
```

**Comment by peerdavid** [comment]
Do you use a python version < 3.6 (f-strings are supported since 3.6)?
But, its not really necessary to use f-strings so I changed those. Latest version should work...

**Comment by peerdavid** [comment]
I close this issue now due to inactivity. Feel free to reopen it.
