### ISSUE TITLE
I dont seem to get any connection

### ISSUE THREAD

**Issue by axkibe** [peerdavid/remapy#60]
```
./launch.sh 
remapy ROOT: /home/axel/remapy
(Warning) Failed to publish subscriber.
'NoneType' object is not iterable
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/axel/remapy/gui/file_explorer.py", line 490, in btn_sync_click
    root, self.is_online = self.item_manager.get_root(force=True)
  File "/home/axel/remapy/model/item_manager.py", line 41, in get_root
    self._clean_local_items(metadata_list)
  File "/home/axel/remapy/model/item_manager.py", line 147, in _clean_local_items
    online_ids = [metadata["ID"] for metadata in metadata_list]
TypeError: 'NoneType' object is not iterable
```

**Comment by fpom** [comment]
I have a similar error: when I start remapy is prints
```
remapy ROOT: /home/franck/bin/remapy.d
(Warning) Failed to publish subscriber.
'NoneType' object is not iterable
```
And the interface is stuck at `Syncing all documents...`
I'm using the latest version pulled from the git repo.

**Comment by jeannecolbois** [comment]
I also have the exact same error as fpom (Ubuntu 20.04.4)

I tried uninstalling remapy, getting a fairly old commit (3e012e1d9f6b76b898278f04d6516d2c6f2bcf6b, August 28 2021) and re-install that version, and I still get the same error.  

I attach the output of the install.sh in case that helps in any way. 
[output_install.txt](https://github.com/peerdavid/remapy/files/8391656/output_install.txt)

**Comment by axkibe** [comment]
As I found out, as the Readme says "some" devices started to stop working is when remarkable rolled out a new cloud API.. and this aint it, and by now its likely basically all devices. IMO the readme.md should reflect this before more and more people invest time to just discover it wont work. Also awesome-reMarkable should mark projects that cannot work due to out of date API.. there is also an issue there open to reflect it in the overview..

**Comment by axkibe** [comment]
There has been some progress reverse engineering the new API:

https://github.com/juruen/rmapi#warning-experimental-support-for-the-new-sync-protocol
or
https://github.com/subutux/rmapy/issues/25

Put it's fully conclusive how the state is (a shame remarkable keeps it's API a secret or rolls its out without giving a head info to the community they benefit from also)
